"""last active column for room

Revision ID: c08385e5b1a8
Revises: c464be75d33b
Create Date: 2021-08-16 17:59:28.425457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08385e5b1a8'
down_revision = 'c464be75d33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'last_active')
    # ### end Alembic commands ###
